// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xchslbxjtpldnbahhnop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjaHNsYnhqdHBsZG5iYWhobm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjQ5NDMsImV4cCI6MjA2ODYwMDk0M30.uIcxQOObHwp0T6hRyf8-C8q7dwbY6n1HCydmD-H6L_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});